### ISSUE TITLE
Slugify fails to work

### ISSUE THREAD

**Issue by matyasmatta** [DeutscheGabanna/Obsidian-Daylio-Parser#1]
`NameError: name 'unicode' is not defined`

I'd suggest replacing Slugify with more capable unidecode, for anyone encountering the same error you can edit the slugify library to use unidecode, as such replace the `return(unicode(...` function with `return unidecode(string)` and `from unidecode import unidecode`

**Comment by bgalek** [comment]
you can adopt easy slugification:
```
  return text.toString().toLowerCase()
    .replace(/\s+/g, '-')           // Replace spaces with -
    .replace(/[^\w\-]+/g, '')       // Remove all non-word chars
    .replace(/\-\-+/g, '-')         // Replace multiple - with single -
    .replace(/^-+/, '')             // Trim - from start of text
    .replace(/-+$/, '');            // Trim - from end of text
}
```
