### ISSUE TITLE
Feature Req: Add Folder sorting

### ISSUE THREAD

**Issue by foxtrotluna** [DeutscheGabanna/Obsidian-Daylio-Parser#12]
Hello, I am wondering if you can add the ability to sort the generated markdown files into folders.

I already hacked the existing script to do it myself by adding:
`  pathsplit = re.split(r"\D",day)
   self.path = f"{os.path.join(settings.destination, settings.prefix, pathsplit[0], pathsplit[1])}/{day}{settings.suffix}.md"
`
into write_md.py (along with some other customizations).
This sorts the files into a YYYY/MM format, keeping the YYYY-MM-DD.md filename.

I noticed you're rewriting the application in a Pull Request so I've refrained from creating a pull request myself. I have files for every day since 2018, so keeping them in a nicer structure would be useful for me personally. Happy for it to be a command-line switch too for people to keep a flatter structure.

**Comment by DeutscheGabanna** [comment]
I'm very happy the script has helped you. As you noticed, I'm in the middle of a rewrite. Once it is merged, I can add the hierarchical folder structures as you suggest. If you'd like to contribute, that'd be awesome too. Just wait for the merge, though.

**Comment by DeutscheGabanna** [comment]
Hey, sorry to be so late to the party. The feature has been added in v.0.1 ef13953e
