### ISSUE TITLE
performance optimization

### ISSUE THREAD

**Issue by bgalek** [DeutscheGabanna/Obsidian-Daylio-Parser#2]
Let's calculate checksum csv row so when we rereun our script we don't touch files that don't need any update

i.e.
csv row 1 => hash(423db) => file.423db.md
csv row 2 => hash(537a) => file.537a.md
csv row 3 => hash(7434d) => file.7434d.md

**Comment by DeutscheGabanna** [comment]
Are you ok with my proposition?
